Ext.define('Common.service.IconCls', {
    alternateClassName: 'IconCls',
    singleton: true,

    create: 'x-fa fa-file',
    update: 'x-fa fa-edit',
    delete: 'x-fa fa-trash',
    save: 'x-fa fa-save',
    cancel: 'x-fa fa-times',
    refresh: 'x-fa fa-redo',
    search: 'x-fa fa-search',
    add: 'x-fa fa-plus',
    language: 'x-fa fa-globe',
    undo: 'x-fa fa-undo',
    export: 'x-fa fa-file-export',
    import: 'x-fa fa-file-import',
    download: 'x-fa fa-download',
    upload: 'x-fa fa-upload',
    help: 'x-fa fa-question-circle',
    history: 'x-fa fa-history',
    logout: 'x-fa fa-sign-out-alt',
    user: 'x-fa fa-user',
    group: 'x-fa fa-users',
    role: 'x-fa fa-user-tag',
    permission: 'x-fa fa-lock',
    setting: 'x-fa fa-cog',
    info: 'x-fa fa-info-circle',
    success: 'x-fa fa-check-circle',
    warning: 'x-fa fa-exclamation-triangle',
    error: 'x-fa fa-exclamation-circle',
    question: 'x-fa fa-question-circle',
    lock: 'x-fa fa-lock',
    unlock: 'x-fa fa-unlock',
    edit: 'x-fa fa-edit',
    delete: 'x-fa fa-trash',
    add: 'x-fa fa-plus',
    remove: 'x-fa fa-minus',
    up: 'x-fa fa-arrow-up',
    down: 'x-fa fa-arrow-down',
    left: 'x-fa fa-arrow-left',
    right: 'x-fa fa-arrow-right',
    qrCode: 'x-fa fa-qrcode',
    done: 'x-fa fa-check'

})