import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider, { useAuth } from "@/components/AuthProvider";
import Nav from '@/app/nav';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const env = process.env;

    return (
        <html lang="en">
            <AuthProvider {
                ...{
                    authority: env.NEXT_PUBLIC_AUTH_ISSUER_BASE_URL,
                    client_id: env.NEXT_PUBLIC_AUTH_CLIENT_ID,
                    redirect_uri: env.NEXT_PUBLIC_BASE_URL,
                    scope: env.NEXT_PUBLIC_AUTH_SCOPE
                }
            }>
                <body>
                    <header>
                        <Nav />
                    </header>
                    <div className="container">{children}</div>
                </body>
            </AuthProvider >
        </html>
    );
}
